version: "3.9"

services:
  cache:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    hostname: redis
    restart: always

  db:
    image: postgres
    volumes:
      - postgres_data:/data
    ports:
      - "${SEQUELIZE_PORT}:5432"
    hostname: postgres
    restart: always
    environment:
      POSTGRES_DB: ${SEQUELIZE_DATABASE}
      POSTGRES_USER: ${SEQUELIZE_USERNAME}
      POSTGRES_PASSWORD: ${SEQUELIZE_PASSWORD}

  my_content_api:
    depends_on:
      - cache
      - db
    image: my_content_api
    volumes:
      - ${API_HOME}:${PATH_TO_UPLOADS}
    ports:
      - "${API_PORT}:${PORT}"
    restart: always
    environment:
      ADMIN_GROUP_ID: ${ADMIN_GROUP_ID}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
      API_PREFIX: ${API_PREFIX}
      ID_TOKEN_VALIDITY_SECONDS: ${ID_TOKEN_VALIDITY_SECONDS}
      IMAGE_UPLOAD_FIELD_NAME: ${IMAGE_UPLOAD_FIELD_NAME}
      LOCAL_NETWORK_IP: ${LOCAL_NETWORK_IP}
      PATH_TO_UPLOADS: ${PATH_TO_UPLOADS}
      PATH_TO_THUMBNAILS: ${PATH_TO_THUMBNAILS}
      PORT: ${PORT}
      RATE_LIMIT_MAX: ${RATE_LIMIT_MAX}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      SECRET: ${SECRET}
      SEQUELIZE_DIALECT: ${SEQUELIZE_DIALECT}
      SEQUELIZE_STORAGE: ${SEQUELIZE_STORAGE}
      SEQUELIZE_DATABASE: ${SEQUELIZE_DATABASE}
      SEQUELIZE_LOGGING: ${SEQUELIZE_LOGGING}
      SEQUELIZE_USERNAME: ${SEQUELIZE_USERNAME}
      SEQUELIZE_PASSWORD: ${SEQUELIZE_PASSWORD}
      SEQUELIZE_HOST: ${SEQUELIZE_HOST}
      SEQUELIZE_PORT: ${SEQUELIZE_PORT}
volumes:
  redis_data: {}
  postgres_data: {}