pipeline {
  agent {
    node { label 'master' }
  }
  stages {
    stage('docker build') {
      steps {
        sh 'docker build -t my_content_api .'
      }
    }
    stage('docker run') {
      steps {
        sh 'docker stop my_content_api || true'
        sh 'docker rm my_content_api || true'
        sh 'docker run -it -d -p 8001:80 --name my_content_api \
            -v /home/uploads:/app/uploads my_content_api'
      }
    }
  }
}
